# Generated by Django 5.0.4 on 2024-09-30 11:44

from django.db import migrations

# Generated by Django 5.0.4 on 2024-09-28 09:20

from django.db import migrations, transaction

def add_EmployeeDepartments(apps, schema_editor):
    Department = apps.get_model('leave_management','EmployeeDepartments')
  

    # Add Department
    with transaction.atomic():
        try:
            # Add Departments
            finance = Department.objects.create(
                name='finance',
                hod=None
            )
            
            operations = Department.objects.create(
                  name='operations',
                hod=None
              
            )

            # Add Employees
            logistics = Department.objects.create(
                name='Logistics',
                hod=None
        
            )

            it= Department.objects.create(
                name='it',
                hod=None
             
            )

        except Exception as e:
            print(f"An error occurred: {e}")
            raise  # Reraise the exception to maintain transaction integrity

class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_employee_department'),
    ]

    operations = [
        migrations.RunPython(add_EmployeeDepartments),
    ]
